apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zrjrok1ly-python 
  janus-idp.io/tekton: zrjrok1ly-python
  backstage.io/kubernetes-id: zrjrok1ly-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zrjrok1ly-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml